name: eCPU CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Code Quality & Linting
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 isort
    
    - name: Check Python formatting with Black
      run: |
        black --check verification/ scripts/
    
    - name: Lint Python code with flake8
      run: |
        flake8 verification/ scripts/
    
    - name: Install Verilator
      run: |
        sudo apt-get update
        sudo apt-get install -y verilator
    
    - name: Lint SystemVerilog/Verilog files
      run: |
        # Basic syntax check with Verilator
        lint_failed=0
        find rtl/ -name "*.sv" -o -name "*.v" | head -5 | while read file; do
          echo "Checking $file"
          if ! verilator --lint-only -Wall "$file"; then
            echo "Lint failed for $file"
            lint_failed=1
          fi
        done
        if [ $lint_failed -eq 1 ]; then
          echo "SystemVerilog linting failed"
          exit 1
        fi

  unit-tests:
    runs-on: ubuntu-latest
    name: Unit Tests
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y verilator gtkwave
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cocotb cocotb-test pytest pytest-cov pytest-xdist
    
    - name: Run ALU tests
      run: |
        cd verification/cocotb
        if [ -f test_alu.py ]; then
          python -m pytest test_alu.py -v
        else
          echo "ALU tests not yet implemented - creating placeholder"
          echo "TODO: Implement ALU tests" > test_results.txt
        fi
    
    - name: Run Register File tests
      run: |
        cd verification/cocotb
        if [ -f test_regfile.py ]; then
          python -m pytest test_regfile.py -v
        else
          echo "Register file tests not yet implemented - creating placeholder"
          echo "TODO: Implement register file tests" >> test_results.txt
        fi
    
    - name: Generate test coverage
      run: |
        cd verification
        if ls cocotb/test_*.py 1> /dev/null 2>&1; then
          python -m pytest --cov=../rtl --cov-report=html --cov-report=xml
        else
          echo "No test files found - skipping coverage"
        fi
      continue-on-error: true
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./verification/coverage.xml
        fail_ci_if_error: false

  synthesis-check:
    runs-on: ubuntu-latest
    name: Synthesis Check
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install synthesis tools
      run: |
        sudo apt-get update
        sudo apt-get install -y yosys fpga-icestorm nextpnr-ice40
    
    - name: Check basic synthesis
      run: |
        # Quick synthesis check for individual modules
        synthesis_failed=0
        
        # Check if ALU module exists and can be synthesized
        if [ -f rtl/core/alu.sv ]; then
          echo "module test_alu; alu u_alu(.operand_a_i(32'h0), .operand_b_i(32'h0), .alu_op_i(4'h0), .result_o(), .zero_o(), .negative_o(), .overflow_o(), .carry_o()); endmodule" > test_synth.v
          if ! yosys -p "read_verilog rtl/core/alu.sv test_synth.v; hierarchy -top test_alu; proc; opt; stat"; then
            echo "ALU synthesis check failed"
            synthesis_failed=1
          fi
          rm -f test_synth.v
        else
          echo "ALU module not found - skipping synthesis check"
        fi
        
        if [ $synthesis_failed -eq 1 ]; then
          echo "Synthesis checks failed"
          exit 1
        fi
    
    - name: iCEBreaker synthesis check
      run: |
        # This will fail until we have a complete top-level, but checks tool installation
        make synth-check || echo "Full synthesis not yet available - this is expected during development"
      continue-on-error: true

  integration-tests:
    runs-on: ubuntu-latest
    name: Integration Tests
    needs: [unit-tests]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y verilator
        python -m pip install --upgrade pip
        pip install cocotb cocotb-test pytest
    
    - name: Run integration tests
      run: |
        # Check if integration tests exist
        if [ -d verification/integration ]; then
          cd verification/integration
          python -m pytest -v
        else
          echo "Integration tests will be added as modules are completed"
        fi
      continue-on-error: true

  documentation:
    runs-on: ubuntu-latest
    name: Documentation Build
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install documentation tools
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme pandoc
        sudo apt-get install -y pandoc
    
    - name: Build documentation
      run: |
        make docs || echo "Documentation build not yet configured"
      continue-on-error: true
    
    - name: Check README and important docs
      run: |
        # Ensure key documentation files exist and are valid
        test -f README.md || exit 1
        test -f TODO.md || exit 1
        test -f PROJECT_SPEC.md || exit 1
        echo "Key documentation files present"

  project-status:
    runs-on: ubuntu-latest
    name: Project Status
    needs: [lint, unit-tests, synthesis-check]
    if: always()
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Project status summary
      run: |
        echo "=== eCPU Project Status ==="
        echo "Lint job: ${{ needs.lint.result }}"
        echo "Unit tests: ${{ needs.unit-tests.result }}"
        echo "Synthesis check: ${{ needs.synthesis-check.result }}"
        echo ""
        echo "File counts:"
        find rtl/ -name "*.sv" -o -name "*.v" | wc -l | xargs echo "RTL files:"
        find verification/ -name "*.py" | wc -l | xargs echo "Test files:"
        echo ""
        echo "Recent commits:"
        git log --oneline -5 || echo "No git history"
        
        # Fail this job if critical jobs failed
        if [[ "${{ needs.lint.result }}" == "failure" || "${{ needs.unit-tests.result }}" == "failure" || "${{ needs.synthesis-check.result }}" == "failure" ]]; then
          echo "❌ Critical checks failed - PR should not be merged"
          exit 1
        else
          echo "✅ All critical checks passed"
        fi 